export default interface UserObject {
  "id": number,
  "id_str": string,
  "name": string,
  "screen_name": string,
  "location": string | null,
  "url": string | null,
  "description": string | null,
  "translator_type": string | null,
  "protected": boolean,
  "verified": boolean,
  "followers_count": number,
  "friends_count": number,
  "listed_count": number,
  "favourites_count": number,
  "statuses_count": number,
  "created_at": string,
  "utc_offset": string | null,
  "time_zone": string | null,
  "geo_enabled": boolean,
  "lang": string | null,
  "contributors_enabled": boolean,
  "is_translator": boolean,
  "profile_background_color": string | null,
  "profile_background_image_url": string | null,
  "profile_background_image_url_https": string | null,
  "profile_background_tile": false,
  "profile_link_color": string | null,
  "profile_sidebar_border_color": string | null,
  "profile_sidebar_fill_color": string | null,
  "profile_text_color": string | null,
  "profile_use_background_image": true,
  "profile_image_url": string | null,
  "profile_image_url_https": string | null,
  "profile_banner_url": string | null,
  "default_profile": true,
  "default_profile_image": false,
  "following": null,
  "follow_request_sent": null,
  "notifications": null,
  "withheld_in_countries": [],
  "location_analyzed": {
    "in_english": string,
    "lang_detected": string,
    "latitude": number | null,
    "longitude": number | null,
    "country_name": string,
    "country_code": string,
  },
  "demographics": {
    "gender": {
      "male": number,
      "female": number,
    },
    "age": {
      "<=18": number,
      "19-29": number,
      "30-39": number,
      ">=40": number,
    },
    "org": {
      "non-org": number,
      "is-org": number,
    }
  },
  "age_predicted": string,
  "gender_predicted": string,
  "org_predicted": string,
}